(source gnu)
(source melpa)
(source org)

;; Package install
(depends-on "cask")
(depends-on "cask-mode")
(depends-on "paradox")
(depends-on "epm")

;; Org Mode
(depends-on "org-plus-contrib")
(depends-on "htmlize")
(depends-on "ox-pandoc")
(depends-on "ox-qmd")
(depends-on "ox-gfm")
(depends-on "ox-twbs")
(depends-on "ox-reveal")
(depends-on "ob-http")
(depends-on "org-review")
(depends-on "org-tree-slide")
(depends-on "org-dashboard")
(depends-on "org-random-todo")
(depends-on "org-attach-screenshot")
(depends-on "org-grep")
(depends-on "org-clock-today")
(depends-on "org-recent-headings")
(depends-on "orgbox")
(depends-on "orgnav")
(depends-on "toc-org")
(depends-on "org-web-tools")
(depends-on "org-bullets")

;; Major modes
(depends-on "python-mode")
(depends-on "perl-mode")
(depends-on "csharp-mode")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "csv-mode")
(depends-on "es-mode")
(depends-on "markdown-mode")
(depends-on "po-mode")
(depends-on "gnuplot-mode")
(depends-on "ess")
(depends-on "yatex")
(depends-on "cmake-mode")
(depends-on "php-mode")

;; Development
(depends-on "origami")
(depends-on "yasnippet")
(depends-on "editorconfig")
(depends-on "modern-cpp-font-lock")
(depends-on "0xc")
(depends-on "ascii")
(depends-on "uuid")
(depends-on "describe-number")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "tern")
(depends-on "tern-auto-complete")
(depends-on "web-mode")
(depends-on "web-beautify")
(depends-on "gist")
(depends-on "help-fns+")
(depends-on "helpful")
(depends-on "git-commit")
(depends-on "elisp-lint")
(depends-on "package-lint")
(depends-on "magit")
(depends-on "cov")
(depends-on "ggtags")
(depends-on "gxref") ;; emacs 25.1 or later
(depends-on "bug-hunter")
;; (depends-on "ac-rtags")
;; (depends-on "flycheck-rtags")

;; Helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-bm")
(depends-on "helm-css-scss")
(depends-on "helm-descbinds")
(depends-on "helm-emmet")
(depends-on "helm-flycheck")
(depends-on "helm-google")
(depends-on "helm-gtags")
(depends-on "helm-pass")
(depends-on "helm-projectile")
;; (depends-on "helm-rtags")
(depends-on "helm-swoop")

;; OSX support
(depends-on "osx-lib")
(depends-on "osx-trash")
(depends-on "osx-dictionary")

;; Editing suport
(depends-on "aggressive-indent")
(depends-on "ws-butler")
(depends-on "flyspell")
(depends-on "flyspell-correct-helm")
(depends-on "auto-complete")
(depends-on "auto-complete-clang")
(depends-on "ac-js2")
(depends-on "migemo")
(depends-on "edit-color-stamp")
;; (depends-on "parinfer")

;; Visualize
(depends-on "volatile-highlights")
(depends-on "highlight-symbol")
(depends-on "fancy-narrow")
(depends-on "smartparens")
(depends-on "mic-paren")
(depends-on "shut-up")
;; (depends-on "diminish")
(depends-on "delight")
(depends-on "rainbow-mode")
(depends-on "centered-cursor-mode")
(depends-on "hide-lines")
(depends-on "undo-tree")
(depends-on "which-key")
(depends-on "back-button")
(depends-on "all-the-icons-dired")

;; System related
(depends-on "dired-narrow")
(depends-on "dired-du")
(depends-on "gited")
(depends-on "neotree")
(depends-on "network-watch")
(depends-on "system-packages")

;; Frame and windows
(depends-on "popwin")
(depends-on "moom" :git "https://github.com/takaxp/moom.git")
(depends-on "spaceline-all-the-icons")
(depends-on "tabbar")

;; Robustness
(depends-on "backup-each-save")
(depends-on "session")

;; Efficiency
(depends-on "selected")
(depends-on "replace-from-region")
(depends-on "quickrun")
(depends-on "latex-math-preview")
(depends-on "smart-mark")
(depends-on "syntax-subword")
(depends-on "goto-chg")
(depends-on "postpone" :git "https://github.com/takaxp/postpone.git")

;; Applications
(depends-on "lingr")
(depends-on "bm")
(depends-on "ag")
(depends-on "japanese-holidays")
(depends-on "calfw-org" :git "https://github.com/takaxp/emacs-calfw.git" :files ("calfw-org.el"))
(depends-on "emacs-utilis" :git "https://github.com/syohex/emacs-utils.git" :files ("pomodoro.el" "eshell-util.el"))
(depends-on "google-this")
(depends-on "google-maps")
(depends-on "japanlaw")
(depends-on "emacsql-sqlite")
(depends-on "w3m")
(depends-on "sunshine")

;; Log
(depends-on "keyfreq")
;; (depends-on "sauron")

;; 2017-10-03 updated.
