;; #+date: 2019-02-26

(source gnu)
(source melpa)
(source org)
;; Private recipes, not in MELPA (private MELPA: https://pxaka.tokyo/melpa)
;; (source "takaxp" "~/devel/git/melpa/packages/")
;; (source "takaxp" "https://pxaka.tokyo/melpa/packages/")
;; (source "stable" "https://stable.melpa.org/packages/")
;; (source "mirror" "https://www.mirrorservice.org/sites/melpa.org/packages/")
;; (source "mstable" "https://www.mirrorservice.org/sites/stable.melpa.org/packages/")

;; Fundamental
(depends-on "postpone"     :git "https://github.com/takaxp/postpone.git")
(depends-on "ascii"        :git "https://github.com/takaxp/ascii.git")
(depends-on "help-fns+"    :git "https://github.com/takaxp/help-fns-plus.git")
(depends-on "emacs-utils"  :git "https://github.com/syohex/emacs-utils.git")
(depends-on "git-complete" :git "https://github.com/zk-phi/git-complete.git")

;; Testing
(depends-on "htprofile"    :git "https://github.com/takaxp/htprofile.git")
(depends-on "yequake"      :git "https://github.com/alphapapa/yequake.git")

;; Package install
(depends-on "cask")
(depends-on "cask-mode")
(depends-on "paradox")
(depends-on "use-package")
;; (depends-on "epl")
;; (depends-on "epm")

;; Org Mode
;; (depends-on "org-plus-contrib")
(depends-on "htmlize")
(depends-on "ox-pandoc")
(depends-on "ox-qmd")
(depends-on "ox-gfm")
(depends-on "ox-twbs")
(depends-on "ox-reveal")
(depends-on "ox-hugo")
(depends-on "ox-ipynb" :git "https://github.com/jkitchin/ox-ipynb.git")
(depends-on "ob-http")
(depends-on "ob-async")
(depends-on "org-review")
(depends-on "org-tree-slide")
(depends-on "org-dashboard")
(depends-on "org-random-todo")
(depends-on "org-attach-screenshot")
(depends-on "org-download")
(depends-on "org-grep")
(depends-on "org-clock-today")
(depends-on "org-recent-headings")
(depends-on "orgbox")
(depends-on "orgnav")
(depends-on "poporg")
(depends-on "toc-org")
(depends-on "org-web-tools")
(depends-on "org-bullets")
(depends-on "org-edna")
(depends-on "org-fancy-priorities")
(depends-on "calfw-org")
(depends-on "calfw")
(depends-on "org-bookmark-heading")
(depends-on "org-emms")
(depends-on "easy-hugo")
(depends-on "org-projectile")
(depends-on "org-trello")

;; Major modes
(depends-on "python-mode")
(depends-on "perl-mode")
(depends-on "csharp-mode")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "csv-mode")
(depends-on "es-mode")
(depends-on "markdown-mode")
;; (depends-on "po-mode")
(depends-on "gnuplot-mode")
(depends-on "ess")
(depends-on "yatex")
(depends-on "cmake-mode")
(depends-on "php-mode")

;; Development
(depends-on "origami")
(depends-on "yasnippet")
(depends-on "editorconfig")
(depends-on "modern-cpp-font-lock")
(depends-on "0xc")
(depends-on "uuid")
(depends-on "describe-number")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "flycheck-clang-tidy")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "tern")
(depends-on "tern-auto-complete")
(depends-on "web-mode")
(depends-on "web-beautify")
(depends-on "gist")
(depends-on "helpful")
(depends-on "git-commit")
(depends-on "elisp-lint")
(depends-on "package-lint")
(depends-on "magit")
(depends-on "cov")
(depends-on "ggtags")
(depends-on "gxref") ;; emacs 25.1 or later
(depends-on "bug-hunter")
(depends-on "clang-format")
(depends-on "format-all")
(depends-on "emr")
(depends-on "rmsbolt")
;; (depends-on "ac-rtags")
;; (depends-on "flycheck-rtags")
(depends-on "ediff-side-by-side" :git "https://github.com/tarao/ediff-side-by-side-el.git")
(depends-on "diffview")

;; Helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-bm")
(depends-on "helm-descbinds")
(depends-on "helm-flycheck")
(depends-on "helm-gtags")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "helm-selected")
(depends-on "helm-pass")
(depends-on "helm-emmet")
(depends-on "helm-emms")
(depends-on "helm-pass")
(depends-on "helm-dired-history")

;; (depends-on "helm-google")
;; (depends-on "helm-ghq")
;; (depends-on "helm-css-scss")
;; (depends-on "helm-rtags")

;; OSX support
(depends-on "osx-lib")
(depends-on "osx-trash")
(depends-on "osx-dictionary")

;; Editing suport
(depends-on "aggressive-indent")
(depends-on "ws-butler")
(depends-on "flyspell")
(depends-on "flyspell-correct-helm")
(depends-on "auto-complete")
(depends-on "auto-complete-clang")
(depends-on "ac-js2")
(depends-on "migemo")
(depends-on "edit-color-stamp")
(depends-on "tiny")
(depends-on "olivetti")
;; (depends-on "parinfer")
(depends-on "hydra")

;; Visualize
(depends-on "volatile-highlights")
(depends-on "highlight-symbol")
(depends-on "fancy-narrow")
(depends-on "smartparens")
(depends-on "mic-paren")
(depends-on "shut-up")
(depends-on "delight") ;; or diminish
(depends-on "dimmer")
(depends-on "rainbow-mode")
(depends-on "centered-cursor-mode")
(depends-on "hide-lines")
(depends-on "undo-tree")
(depends-on "which-key")
(depends-on "back-button")
(depends-on "font-lock+" :git "https://github.com/emacsmirror/font-lock-plus.git")
(depends-on "all-the-icons-dired")
(depends-on "smooth-scroll")
(depends-on "manage-minor-mode")
(depends-on "git-gutter-fringe")
(depends-on "isolate")
(depends-on "logview")
;; (depends-on "spaceline")
(depends-on "doom-modeline")
(depends-on "disk-usage")

;; System related
(depends-on "dired-narrow")
(depends-on "dired-du")
(depends-on "dired-recent")
(depends-on "neotree")
(depends-on "network-watch")
;; (depends-on "gited")
(depends-on "find-file-in-project")

;; Frame and windows
(depends-on "popwin")
(depends-on "shackle")
(depends-on "tabbar")
(depends-on "moom")
(depends-on "doom-modeline")
(depends-on "frame-tabs")
;; (depends-on "spaceline-all-the-icons")
;; (depends-on "exwm") ;; failed to instal ... Bad Request

;; Robustness
(depends-on "session")
(depends-on "backup-each-save")

;; Efficiency
(depends-on "selected")
(depends-on "replace-from-region")
(depends-on "quickrun")
(depends-on "latex-math-preview")
(depends-on "bratex" :git "https://github.com/sbrisard/bratex.git")
(depends-on "smart-mark")
(depends-on "syntax-subword")
(depends-on "goto-chg")
(depends-on "esup")
(depends-on "initchart" :git "https://github.com/yuttie/initchart.git")


;; Applications
(depends-on "lingr")
(depends-on "gitter")
(depends-on "bm")
(depends-on "ag")
(depends-on "google-this")
(depends-on "japanese-holidays")
(depends-on "emacsql-sqlite")
(depends-on "w3m")
(depends-on "sunshine")
(depends-on "emms")
(depends-on "pass")
(depends-on "gif-screencast")
(depends-on "keycast")
(depends-on "pdf-tools")
;; (depends-on "japanlaw")
;; (depends-on "google-maps")

;; Log
(depends-on "keyfreq")
;; (depends-on "sauron")

;; Examples
;;  :git "https://.../hoge.git"
;;  :ref "abcdefg"
;;  :branch "master"
;;  files ("*.el" (:exclude "hoge.el"))
